/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFramePrincipal.java
 *
 * Created on 10-sep-2011, 9:50:53
 */

package com.rnasystems.projects.dragdropdesign.vista;

import java.awt.BorderLayout;
import java.io.PrintWriter;
import java.io.StringWriter;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.linet.api.swing.lookandfeel.WindowUtilities;
import com.rnasystems.projects.dragdropdesign.vista.ayuda.JDialogAcercaDe;
import com.rnasystems.projects.dragdropdesign.vista.nuevoProyecto.PanelProyecto;
import com.rnasystems.projects.dragdropdesign.vista.util.VistaUtil;

/**
 *
 * @author RM-RCMJ
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form JFramePrincipal */
    public JFramePrincipal() {
        initComponents();
        myInit();
    }

    public void myInit(){
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //new CMenubar(jMenuArchivo);
        jPanelPrincipal.setLayout(new BorderLayout());
        panelProyecto = new PanelProyecto();
        jDialogAcercaDe = new JDialogAcercaDe(this, true);
        jDialogAcercaDe.setVisible(false);

        //
        setLayout(null);
        setBoundsComponentes();
    }

    public void setBoundsComponentes(){
        setBoundsMenuBar();
        setBoundsPanelPrincipal();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevoProyecto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevoProyecto.setText("Nuevo Proyecto");
        jMenuItemNuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoProyectoActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemNuevoProyecto);

        jMenuBar1.add(jMenuArchivo);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Configuraciones");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoProyectoActionPerformed
        jPanelPrincipal.removeAll();
        if (panelProyecto == null) {
            panelProyecto = new PanelProyecto();
        }
        jPanelPrincipal.add(panelProyecto, BorderLayout.CENTER);
        jPanelPrincipal.validate();
        jPanelPrincipal.repaint();
    }//GEN-LAST:event_jMenuItemNuevoProyectoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      jDialogAcercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void setBoundsMenuBar(){
        jMenuBar1.setBounds(0,0, VistaUtil.WIDTH_SCREEN,VistaUtil.HEIGHT_MENU_BAR);
    }

    public void setBoundsPanelPrincipal(){
        jPanelPrincipal.setBounds(0,VistaUtil.HEIGHT_MENU_BAR, VistaUtil.WIDHT_PANEL_PRINCIPAL,VistaUtil.HEIGHT_PANEL_PRINCIPAL);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					WindowUtilities.setNativeLookAndFeel();
					new JFramePrincipal().setVisible(true);
				} catch (Exception ex) {
					ex.printStackTrace();
					StringWriter errors = new StringWriter();
					ex.printStackTrace(new PrintWriter(errors));
					JOptionPane.showMessageDialog(null, "Error when launch app.\n"+errors.toString());
					System.exit(0);
				}
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemNuevoProyecto;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
    private PanelProyecto panelProyecto;
    private JDialogAcercaDe jDialogAcercaDe;
}
