/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelDisenio.java
 *
 * Created on 10-sep-2011, 12:44:54
 */

package com.rnasystems.projects.dragdropdesign.vista.nuevoProyecto.disenio;

import java.awt.Graphics;
import javax.swing.JButton;
import javax.swing.JPanel;
import com.rnasystems.projects.dragdropdesign.controlador.panelDisenio.CLabelPosicionCursor;
import com.rnasystems.projects.dragdropdesign.controlador.panelDisenio.CPanelDisenio;
import com.rnasystems.projects.dragdropdesign.vista.paleta.PaletaPanelColapsable;
import com.rnasystems.projects.dragdropdesign.vista.util.VistaUtil;

/**
 *
 * @author RM-RCMJ
 */
public class PanelDisenio extends javax.swing.JPanel {

    /** Creates new form PanelDisenio */
    public PanelDisenio() {
        initComponents();
        new CPanelDisenio(this);
        new CLabelPosicionCursor(jLabel1, jPanelDraggedComponentes);
        setBoundsComponentes();
    }

    public void setBoundsComponentes(){
       setLayout(null);
       setBoundsJLabelCoordenadasCursor();
       setBoundsJPanelDraggedComponentes();
       setBoundsJButtonLimpiar();
       setBoundsPaletaPanelColapsable1();
    }

    public void setBoundsJLabelCoordenadasCursor(){
        jLabel1.setBounds(VistaUtil.X_LABEL_COORDENADAS,VistaUtil.Y_LABEL_COORDENADAS,
                         VistaUtil.WIDHT_LABEL_COORDENADAS,VistaUtil.HEIGHT_LABEL_COORDENADAS);
    }

    public void setBoundsJButtonLimpiar(){
        jButton1.setBounds(VistaUtil.X_BUTTON_LIMPIAR,VistaUtil.Y_BUTTON_LIMPIAR,VistaUtil.WIDHT_BUTTON_LIMPIAR,VistaUtil.HEIGHT_BUTTON_LIMPIAR);
    }

    public void setBoundsJPanelDraggedComponentes(){
        jPanelDraggedComponentes.setBounds(VistaUtil.X_PANEL_DRAGGED,VistaUtil.Y_PANEL_DRAGGED, VistaUtil.WIDHT_PANEL_DRAGGED,VistaUtil.HEIGHT_PANEL_DRAGGED);
    }
    public void setBoundsPaletaPanelColapsable1(){
        paletaPanelColapsable1.setBounds(VistaUtil.X_PANEL_PALETA,VistaUtil.Y_PANEL_PALETA, VistaUtil.WIDHT_PANEL_PALETA,VistaUtil.HEIGHT_PANEL_PALETA);
    }
//    public void paint(Graphics g) {
//      g.drawOval(100, 100, 200, 200);
//    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paletaPanelColapsable1 = new com.rnasystems.projects.dragdropdesign.vista.paleta.PaletaPanelColapsable();
        jPanelDraggedComponentes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        setLayout(null);

        jLabel1.setText("----");
        add(jLabel1);
        jLabel1.setBounds(10, 15, 207, 14);
        add(paletaPanelColapsable1);
        paletaPanelColapsable1.setBounds(820, 11, 208, 630);

        jPanelDraggedComponentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelDraggedComponentesLayout = new javax.swing.GroupLayout(jPanelDraggedComponentes);
        jPanelDraggedComponentes.setLayout(jPanelDraggedComponentesLayout);
        jPanelDraggedComponentesLayout.setHorizontalGroup(
            jPanelDraggedComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanelDraggedComponentesLayout.setVerticalGroup(
            jPanelDraggedComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        add(jPanelDraggedComponentes);
        jPanelDraggedComponentes.setBounds(10, 40, 792, 601);

        jButton1.setText("Limpiar");
        add(jButton1);
        jButton1.setBounds(735, 11, 67, 23);
    }// </editor-fold>//GEN-END:initComponents

    public PaletaPanelColapsable getPaletaPanelColapsable1() {
        return paletaPanelColapsable1;
    }

    public void setPaletaPanelColapsable1(PaletaPanelColapsable paletaPanelColapsable1) {
        this.paletaPanelColapsable1 = paletaPanelColapsable1;
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDraggedComponentes;
    private com.rnasystems.projects.dragdropdesign.vista.paleta.PaletaPanelColapsable paletaPanelColapsable1;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanelDraggedComponentes() {
        return jPanelDraggedComponentes;
    }

    public void setjPanelDraggedComponentes(JPanel jPanelDraggedComponentes) {
        this.jPanelDraggedComponentes = jPanelDraggedComponentes;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    

}
