/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelGrid.java
 *
 * Created on 16-sep-2011, 14:38:23
 */
package com.rnasystems.projects.dragdropdesign.modelo;

import java.util.ArrayList;

import com.linet.api.swing.component.dragdrop.DragDropComponent;

/**
 *
 * @author RM-RCMJ
 */
public class PanelGrid extends javax.swing.JPanel{

    /** Creates new form PanelGrid */
    public PanelGrid() {
        initComponents();
        listaComponenteIcefaceses = new ArrayList<DragDropComponent>();
        max_alto = new ArrayList<Integer>();
        max_ancho = new ArrayList<Integer>();
        
    }

    public void agregaComponente(DragDropComponent componenteIcefaces) {
        add(componenteIcefaces.getComponent());
        listaComponenteIcefaceses.add(componenteIcefaces);
    }

    public void limpiaListaComponenteIcefaceses() {
        if (listaComponenteIcefaceses != null && listaComponenteIcefaceses.size() > 0) {
            listaComponenteIcefaceses.clear();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    public ArrayList<DragDropComponent> getListaComponenteIcefaceses() {
        return listaComponenteIcefaceses;
    }

    public void setListaComponenteIcefaceses(ArrayList<DragDropComponent> listaComponenteIcefaceses) {
        this.listaComponenteIcefaceses = listaComponenteIcefaceses;
    }

    public ArrayList<Integer> getMax_alto() {
        return max_alto;
    }

    public void setMax_alto(ArrayList<Integer> max_alto) {
        this.max_alto = max_alto;
    }

    public ArrayList<Integer> getMax_ancho() {
        return max_ancho;
    }

    public void setMax_ancho(ArrayList<Integer> max_ancho) {
        this.max_ancho = max_ancho;
    }


    private ArrayList<DragDropComponent> listaComponenteIcefaceses;
    private ArrayList<Integer> max_ancho;
    private ArrayList<Integer> max_alto; 

}
