/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogPropiedades.java
 *
 * Created on 17-sep-2011, 15:06:22
 */

package com.rnasystems.projects.dragdropdesign.vista.propiedadesComponente;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author RM-RCMJ
 */
public class JDialogPropiedades extends javax.swing.JDialog {

    /** Creates new form JDialogPropiedades */
    public JDialogPropiedades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(false);
        setSize(400,350);
        centra();
    }

    public void centra() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2,size.height / 2 - getHeight() / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_texo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ancho = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_alto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_x = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_y = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_style = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_cols = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_rows = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 290, 70, 23);

        jButton2.setText("Aceptar");
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 290, 73, 23);

        jLabel1.setText("Texto");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 155, 20);
        getContentPane().add(jTextField_texo);
        jTextField_texo.setBounds(170, 50, 210, 20);

        jLabel2.setText("Ancho");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 155, 20);
        getContentPane().add(jTextField_ancho);
        jTextField_ancho.setBounds(170, 80, 210, 20);

        jLabel3.setText("Alto");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 155, 20);
        getContentPane().add(jTextField_alto);
        jTextField_alto.setBounds(170, 110, 210, 20);

        jLabel4.setText("coordenada x");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 155, 20);
        getContentPane().add(jTextField_x);
        jTextField_x.setBounds(170, 140, 210, 20);

        jLabel5.setText("coordenada y");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 155, 20);
        getContentPane().add(jTextField_y);
        jTextField_y.setBounds(170, 170, 210, 20);

        jLabel6.setText("Estilo");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 155, 20);
        getContentPane().add(jTextField_style);
        jTextField_style.setBounds(170, 200, 210, 20);

        jLabel7.setText("Columnas");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 155, 20);
        getContentPane().add(jTextField_cols);
        jTextField_cols.setBounds(170, 230, 210, 20);

        jLabel8.setText("Id");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 20, 155, 20);
        getContentPane().add(jTextField_id);
        jTextField_id.setBounds(170, 20, 210, 20);
        getContentPane().add(jTextField_rows);
        jTextField_rows.setBounds(170, 260, 210, 20);

        jLabel9.setText("Filas");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 260, 155, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPropiedades dialog = new JDialogPropiedades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_alto;
    private javax.swing.JTextField jTextField_ancho;
    private javax.swing.JTextField jTextField_cols;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_rows;
    private javax.swing.JTextField jTextField_style;
    private javax.swing.JTextField jTextField_texo;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_y;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton2() {
        return jButton2;
    }

}
